### ISSUE TITLE
Deliver Research Synthesis

### ISSUE THREAD

**Issue by simonwex** [adobe/Adobe-Developer-Site#38]
Conclude our first round of stakeholder interviews by synthesizing the results in a sharable document.

**Comment by cassiemc** [comment]
This is done. Can be viewed here: https://docs.google.com/document/d/1ZgOQvf9gZAPHdKlX93YRGEHUxMd9ZA8X_LxaBOL5dGY/edit?usp=sharing

**Comment by cmgeorge16** [comment]
@cassiemc I know that this is different than the overall research synthesis done by the Adobe Design team. Please make sure we flag this document as something that will need to get removed before this repo becomes public. There's material in there that may be contentious to become public and don't believe we have any explicit consent to be able to post those insights publicly.

**Comment by cassiemc** [comment]
@cmgeorge16 I specifically removed names / positions and id'ing info from this doc (as opposed to the original doc you and I worked on) and have posted it publicly as per @simonwex's request. If there's anything else iffy there could you please flag it for us specifically?; I'll leave the rest up to Adobe staff and @simonwex for final vetting.

FWIW, best process for a flagging something in a closed issue would probably be to email Simon directly. I just happened upon this comment by chance. Thanks!
