### ISSUE TITLE
Create a slide deck

### ISSUE THREAD

**Issue by simonwex** [adobe/Adobe-Developer-Site#41]
Create slide deck for sharing take-aways from research phase.

**Comment by cassiemc** [comment]
This has begun, about 1/3 done. @simonwex ping me if you want to see the WIP.

**Comment by cmgeorge16** [comment]
Initial deck is complete, but will get added to over time when we do more research and interviews with customers, get personas and design principles finalized.

This might be separate from one specifically focusing on the Website, but I've focused on the overall "dev portal (website + console)" and initial research synthesis. This is coming from our Adobe Design Developer Ecosystem team's perspective who's looking more holistically across all the experiences.

**Comment by cassiemc** [comment]
The dev site specific deck is complete. (@cmgeorge16 is referring to a different deck above, one with more of an overview of the ecosystem between console & the dev site)

Keynote source file is here (in case you need to adjust, @simonwex): 
[2019-01-13 dev site research synthesis.zip](https://github.com/adobe/Adobe-Developer-Site/files/2753465/2019-01-13.dev.site.research.synthesis.zip)

Pdf is here: 
[2019-01-13 dev site research synthesis.pdf](https://github.com/adobe/Adobe-Developer-Site/files/2753467/2019-01-13.dev.site.research.synthesis.pdf)

**Comment by cassiemc** [comment]
Also for reference the full text-based report can be read here: https://docs.google.com/document/d/11DSilQ8u7ik8y-zrgUAmx8GSt_yguI7lR2a73FEbgAk/edit as per #38
