### ISSUE TITLE
[Helix code] content.children is being deprecated, use content.document instead

### ISSUE THREAD

**Issue by kptdobe** [adobe/Adobe-Developer-Site#45]
Pending task for https://github.com/adobe/helix-pipeline/issues/105

We need to get rid of `content.children` in the pre.js and htl files. We should use `content.document`.

Same exercise has been done for project-helix.io project, see adobe/project-helix.io@6fbfee5 and
adobe/project-helix.io@10c86cb

cc @filmaj

**Comment by filmaj** [comment]
My spectrum branch on my fork has this in place now. As soon as we merge we can close this.

**Comment by filmaj** [comment]
OK, merged the branch we've been working on this week into master. This is now resolved.
