### ISSUE TITLE
Github rate limit reached for local development

### ISSUE THREAD

**Issue by stevengill** [adobe/Adobe-Developer-Site#51]
Unauthenticated github api requests are rate limited at 60 requests per hour. If we were authenticated, we could do 5000 per hour. [Source](https://developer.github.com/v3/#rate-limiting)

I ran into this limit while doing local development.

Suggestion: Let's allow users to set an environment variable with a github personal access token. `hlx up` would grab the variable and pass it along to the pipeline which could use it to make the github api requests.

**Comment by filmaj** [comment]
Shouldn't we file this in a helix project somewhere, probably cli?

**Comment by stevengill** [comment]
yes, of course. https://github.com/adobe/helix-cli/issues/380
