### ISSUE TITLE
[Launch API Docs] Render Launch API Docs in Helix - Go Live

### ISSUE THREAD

**Issue by simonwex** [adobe/Adobe-Developer-Site#8]
Goal: render  https://docs.adobelaunch.com/ with Helix

Content repo is https://github.com/Adobe-Marketing-Cloud/reactor-user-docs

**Comment by kptdobe** [comment]
I created project https://github.com/adobe/Adobe-Developer-Site/projects/1 to organise all the todos related to the deployment of Launch API Docs with Helix.

**Comment by filmaj** [comment]
So the most recent push from this week's hackathon has resulted in:

- this repo's README being rendered on https://stage-developer.helix-demo.xyz/README.html
- the launch doc repo's markdown being rendered at https://stage-developer.helix-demo.xyz/docs/launch/README.html
